# Site settings
title: login.gov
description: Welcome to the Login.gov developer documentation!
github_repo_url: https://github.com/18F/identity-dev-docs # enables "edit this page" button

plugins:
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from

copy_to_destination:
  - node_modules/identity-style-guide/dist/assets

# Pages
collections:
  pages:
    output: true
    permalink: /:path/

# Build settings
kramdown:
  hard_wrap: true

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: documentation
